version: 2

project_name: noteflow-go

builds:
  # Main NoteFlow-Go application
  - id: noteflow
    main: ./cmd/noteflow
    binary: noteflow-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

  # Installer application  
  - id: installer
    main: ./cmd/installer
    binary: noteflow-installer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

archives:
  # Skip default archive creation, we want individual binaries
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: Xafloc
    name: NoteFlow-Go
  draft: false
  prerelease: auto
  name_template: "NoteFlow-Go {{.Version}}"